### ISSUE TITLE
Metric for Managed Cloud Core

### ISSUE THREAD

**Issue by fdevelop** [Sitecore/Sitecore.OperationsSuite#14]
Create automatic health metric for "Managed Cloud Core".

**Short Definition:** Managed Cloud Core - set of systems used for executing [Service Catalog](https://kb.sitecore.net/articles/137210) items. Does not affect customer environments availability.

**Full Definition:** see [reference](https://sitecore1.sharepoint.com/sites/cloudservices/Shared%20Documents/Operations/OPS%20runbooks/Sitecore%20Managed%20Cloud%20(Hosting)/Reference.Managed%20Cloud%20Core.docx?web=1)

**Technical Reference:**
All resources in the following subscription (visible in cloudspoc@sitecore.net):

- ID: `06841065-b1ff-4f84-bf1c-f13d07c59810`
- Name: `Sitecore Cloud - Managed Cloud Core Prod`

**Resources:**

- 1x Resource group: `Hosting-Consumption-REST-API`
   - 1x App Service: `Hosting-Consumption-REST-API` (REST API server)
   - 1x SQL Server: `hosting-consumption-rest-api`
   - 1x SQL Database: `CloudServicesBillingDatabase` (Billing Database)
   - 1x App Insights: `Hosting-Consumption-REST-API` (can be used for monitoring as well)

**Suggested validation test:**

1. Check Web App availability in Azure
2. Check SQL server availability in Azure
3. Check SQL database availability in Azure
4. Ping the following endpoint, use header for authorization:

    ```
    GET https://hosting-consumption-rest-api.azurewebsites.net/api/currency
   X-ScS-Key-Auth: [value of App Service’s ScS.Fundamentals.Security.KeyAuthentication.PrimaryKey setting]
    ```

    Response should be:
    - Status code: `200`
    - Content-Type: `application/json`

**Comment by olegburov** [comment]
Current version `1.1.0` of [Azure Management Libraries for .NET](https://www.nuget.org/packages/Microsoft.Azure.Management.Fluent/) (aka Fluent API) does not support [Azure Application Insights](https://azure.microsoft.com/en-us/services/application-insights/). See [here](https://github.com/Azure/azure-sdk-for-net/issues/3384) for details.

**Comment by olegburov** [comment]
You can get an Azure SQL Server, but can't read its status. See [here](https://github.com/Azure/azure-sdk-for-net/issues/3386) fore details. If it's going to be critical, we can do a PR. Seems like this data is available in JSON response.

**Comment by olegburov** [comment]
We need a separate account with `Read` access right for the `Hosting-Consumption-REST-API` resource group to get status of the above resources.

**Comment by olegburov** [comment]
Done. See e798d96a510768b759839441595afae43940e585 for details.
